on:
  push:
    branches: [ main ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker login --username $GITHUB_ACTOR --password $GITHUB_TOKEN ghcr.io
          docker build --tag ghcr.io/$GITHUB_REPOSITORY .
          docker push ghcr.io/$GITHUB_REPOSITORY
