on:
  push:
    branches: [ main ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker login --username {{ github.actor }} --password {{ github.token }} ghcr.io
          docker build --tag ghcr.io/{{ github.repository }} .
          docker push ghcr.io/{{ github.repository }}
