on:
  push:
    branches: [ main ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker login -u "{{ github.actor }}" -p "{{ github.token }}" ghcr.io
          docker build -t "ghcr.io/{{ github.repository }}" .
          docker push "ghcr.io/{{ github.repository }}"
